import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Curve from "@/components/Curve";
import Landing from "@/components/Home/Landing";
import Description from "@/components/Home/Description";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <main className={styles.main}>
          <Landing />
          <Description />
        </main>
      </Curve>
    </>
  );
}
